parameters:
#    bbit_bootstrap.example.class: BranchBit\BootstrapBundle\Example


#    bbit_bootstrap.example:
#        class: %branch_bit_bootstrap.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    bbit_bootstrap.bootstrap_extension:
        class: BBIT\BootstrapBundle\Twig\BootstrapExtension
        tags:
            - { name: twig.extension }
        arguments: ['@service_container']
